CREATE TABLE IF NOT EXISTS members (
  id CHAR(32) PRIMARY KEY,
  name VARCHAR(80) NOT NULL,
  email VARCHAR(254) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  google_sub VARCHAR(255) NULL,
  CONSTRAINT members_email UNIQUE (email),
  CONSTRAINT members_google_sub UNIQUE (google_sub)
);

CREATE TABLE IF NOT EXISTS sessions (
  token_hash CHAR(64) PRIMARY KEY,
  member_id CHAR(32) NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT sessions_member FOREIGN KEY (member_id) REFERENCES members (id)
);

CREATE TABLE IF NOT EXISTS blocks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prev_hash CHAR(64) NOT NULL,
  hash CHAR(64) NOT NULL,
  entry_type VARCHAR(32) NOT NULL,
  payload JSONB NOT NULL,
  created_at_iso VARCHAR(32) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT blocks_hash UNIQUE (hash)
);

CREATE TABLE IF NOT EXISTS treasury (
  id SMALLINT NOT NULL PRIMARY KEY,
  cash_cents BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS claims (
  member_id CHAR(32) NOT NULL PRIMARY KEY,
  claim_cents BIGINT NOT NULL,
  CONSTRAINT claims_member FOREIGN KEY (member_id) REFERENCES members (id)
);

CREATE TABLE IF NOT EXISTS investments (
  id CHAR(32) NOT NULL PRIMARY KEY,
  symbol VARCHAR(16) NOT NULL,
  name VARCHAR(80) NOT NULL,
  units_micro BIGINT NOT NULL,
  cost_cents BIGINT NOT NULL,
  price_cents BIGINT NOT NULL,
  opened_at TIMESTAMPTZ NOT NULL,
  prior_close_cents BIGINT NULL,
  close_session DATE NULL,
  prior_session DATE NULL
);

CREATE TABLE IF NOT EXISTS investment_marks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  investment_id CHAR(32) NOT NULL,
  price_cents BIGINT NOT NULL,
  marked_at TIMESTAMPTZ NOT NULL,
  session_date DATE NULL,
  CONSTRAINT marks_investment FOREIGN KEY (investment_id) REFERENCES investments (id)
);

CREATE TABLE IF NOT EXISTS payments (
  id CHAR(32) NOT NULL PRIMARY KEY,
  member_id CHAR(32) NOT NULL,
  idempotency_key VARCHAR(64) NOT NULL,
  kind VARCHAR(16) NOT NULL,
  amount_cents BIGINT NOT NULL,
  counterparty_id CHAR(32) NULL,
  phone VARCHAR(15) NULL,
  status VARCHAR(16) NOT NULL,
  checkout_request_id VARCHAR(80) NULL,
  merchant_request_id VARCHAR(80) NULL,
  mpesa_receipt VARCHAR(32) NULL,
  result_code VARCHAR(16) NULL,
  block_id BIGINT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT payments_member_key UNIQUE (member_id, idempotency_key),
  CONSTRAINT payments_checkout UNIQUE (checkout_request_id),
  CONSTRAINT payments_member FOREIGN KEY (member_id) REFERENCES members (id)
);

CREATE TABLE IF NOT EXISTS admins (
  id CHAR(32) PRIMARY KEY,
  name VARCHAR(80) NOT NULL,
  email VARCHAR(254) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT admins_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS desk_sessions (
  token_hash CHAR(64) PRIMARY KEY,
  admin_id CHAR(32) NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT desk_sessions_admin FOREIGN KEY (admin_id) REFERENCES admins (id)
);

CREATE TABLE IF NOT EXISTS loan_products (
  code VARCHAR(16) NOT NULL PRIMARY KEY,
  name VARCHAR(80) NOT NULL,
  interest_percent SMALLINT NOT NULL,
  term_min SMALLINT NOT NULL,
  term_max SMALLINT NOT NULL,
  term_unit VARCHAR(8) NOT NULL,
  minimum_cents BIGINT NOT NULL,
  maximum_cents BIGINT NOT NULL,
  minimum_guarantors SMALLINT NOT NULL,
  coverage_percent SMALLINT NOT NULL,
  fee_percent SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS loan_applications (
  id CHAR(32) NOT NULL PRIMARY KEY,
  member_id CHAR(32) NOT NULL,
  product_code VARCHAR(16) NOT NULL,
  amount_cents BIGINT NOT NULL,
  term_count SMALLINT NOT NULL,
  purpose VARCHAR(500) NOT NULL,
  phone VARCHAR(15) NOT NULL,
  status VARCHAR(32) NOT NULL,
  recommended_cents BIGINT NULL,
  approved_cents BIGINT NULL,
  approved_term SMALLINT NULL,
  risk_rating VARCHAR(16) NULL,
  appraisal_notes VARCHAR(2000) NULL,
  decision_notes VARCHAR(1000) NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT loan_applications_member FOREIGN KEY (member_id) REFERENCES members (id),
  CONSTRAINT loan_applications_product FOREIGN KEY (product_code) REFERENCES loan_products (code)
);

CREATE INDEX IF NOT EXISTS loan_applications_member_idx ON loan_applications (member_id, status);
CREATE INDEX IF NOT EXISTS loan_applications_status_idx ON loan_applications (status, created_at);

CREATE TABLE IF NOT EXISTS loan_guarantors (
  id CHAR(32) NOT NULL PRIMARY KEY,
  application_id CHAR(32) NOT NULL,
  member_id CHAR(32) NOT NULL,
  amount_cents BIGINT NOT NULL,
  status VARCHAR(16) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT loan_guarantors_application FOREIGN KEY (application_id) REFERENCES loan_applications (id),
  CONSTRAINT loan_guarantors_member FOREIGN KEY (member_id) REFERENCES members (id)
);

CREATE INDEX IF NOT EXISTS loan_guarantors_member_idx ON loan_guarantors (member_id, status);
CREATE INDEX IF NOT EXISTS loan_guarantors_application_idx ON loan_guarantors (application_id);

CREATE TABLE IF NOT EXISTS loans (
  id CHAR(32) NOT NULL PRIMARY KEY,
  application_id CHAR(32) NOT NULL,
  member_id CHAR(32) NOT NULL,
  principal_cents BIGINT NOT NULL,
  fee_cents BIGINT NOT NULL,
  net_cents BIGINT NOT NULL,
  status VARCHAR(16) NOT NULL,
  payment_id CHAR(32) NULL,
  disbursed_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT loans_application UNIQUE (application_id),
  CONSTRAINT loans_payment UNIQUE (payment_id),
  CONSTRAINT loans_application_fk FOREIGN KEY (application_id) REFERENCES loan_applications (id),
  CONSTRAINT loans_member FOREIGN KEY (member_id) REFERENCES members (id),
  CONSTRAINT loans_payment_fk FOREIGN KEY (payment_id) REFERENCES payments (id)
);

CREATE INDEX IF NOT EXISTS loans_member_idx ON loans (member_id, status);
